# Python SESSION

In [72]:
#Task1: Write a program that allows you to enter 4 numbers and
#  stores them in a file called “Numbers”

f = open("Numbers.txt","w")

inputNumber = input("Please input 4 numbers and separated by comma!")
arr = inputNumber.split(",")
for x in arr:
    f.write(x)
    f.write("\n")

f.close()

In [4]:
#Task2: Write a program to ask a student for their percentage mark
#  and convert this to a grade. 
# The conversion will be done in a function called mark_grade 

avg = int(input("Please input your percentage mark."))
target = input("Please input your target grade.")

def mark_grade(avg):
    if avg>=81 and avg<=100:
        print("Your Grade is A")
    elif avg>=61 and avg<81:
        print("Your Grade is B")
    elif avg>=41 and avg<61:
        print("Your Grade is C")
    elif avg>=33 and avg<41:
        print("Your Grade is D")
    elif avg>=0 and avg<33:
        print("Your Grade is F")
    else:
        print("Invalid Input mark!")

def compare_target(avg,upper,lower):
      if(avg > upper):
        print("you are above the target!")
      elif(avg>= lower and avg <= upper):
        print("you are at the target!")
      else:
        print("you are below the target!")

def target_grade(target):
    if target == "A":
        upper = 100
        lower = 81 
    elif target == "B":
        upper = 80
        lower = 61
    elif target == "C":
        upper = 60
        lower = 41
    elif target == "E":
        upper = 40
        lower = 33
    elif target == "F":
        upper = 32
        lower = 0
    else:
        print("Invalid Input!")
    compare_target(avg, upper, lower)

    
mark_grade(avg)
target_grade(target)

Your Grade is C
you are at the target!


# NUMPY SESSION

In [51]:
import numpy as np

# Task1: Create a 1D array of numbers from 0 to 9

x = np.arange(0, 10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
# Task2: Create a 3×3 NumPy array of all Boolean value Trues

x = np.ones((3,3), dtype=bool)
x

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [53]:
# Task3: Extract all odd numbers from array of 1-10

x = np.arange(1, 10, 2)
x


array([1, 3, 5, 7, 9])

In [54]:
# Task4: Replace all odd numbers in an array of 1-10 with the value -1

x = np.arange(1, 11)
oddValue = (x%2 == 1)
x[oddValue] = -1
x


array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10])

In [55]:

#Task5: Convert a 1D array to a 2D array with 2 rows

x = np.array([21, 22, 23, 24, 25, 26, 27, 28, 29, 210, 211, 212])
x = x.reshape(2, 6)
x 

array([[ 21,  22,  23,  24,  25,  26],
       [ 27,  28,  29, 210, 211, 212]])

In [56]:
#Task6: Create two arrays a and b, stack these two arrays vertically 
# use the np.dot and np.sum to calculate totals

x = np.arange(1, 10).reshape(3,3)
y = np.arange(10, 19).reshape(3,3)
v = np.dot(x, y)
sum = np.sum(v)
sum

1944

In [57]:
#Task7: Create the following pattern without hardcoding.
# Use only NumPy functions.

x = np.array([1, 2, 3])
pattern = np.r_[np.repeat(x,3), np.tile(x,3)]
pattern

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [58]:
#Task8:  In two arrays a ( 1,2,3,4,5) and b ( 4,5,6,7,8,9) 
# Remove all repeating items present in array b

x = np.array([1,2,3,4,5])
y = np.array([4,5,6,7,8,9])
x = np.setdiff1d(x,y)
x


array([1, 2, 3])

In [59]:
#Task9: Get all items between 3 and 7 from a and b and sum them together
x = np.array([1,2,3,4,5])
x = x[x>=3]
total = x.sum()

y = np.array([4,5,6,7,8,9])
y = y[y<=7]
total = total + y.sum()

total

34